# Generated by Django 6.1 on 2026-09-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True, default='https://github.com/kingshp2002/shapourshah-site', null=True, verbose_name='لینک گیت\u200cهاب'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='static/portfolio_images/', verbose_name='تصویر پروژه'),
        ),
    ]
