# Generated by Django 6.1 on 2026-09-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_portfolio_github_link_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک گیت\u200cهاب'),
        ),
    ]
