# Generated by Django 6.1 on 2026-09-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_portfolio_github_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/', verbose_name='تصویر پروژه'),
        ),
    ]
